name: 'Check dland dining availability'
inputs:
  pushover-token:
    type: string
    required: true
  pushover-user:
    type: string
    required: true
  swid:
    # https://www.democraticmedia.org/sites/default/files/COPPA%20Rule%20Comments%20of%20Children%27s%20Privacy%20Advocates.pdf
    # "From its appearance, the Disney SWID cookie is likely a unique ID number that identifies a particular Web browser"
    type: string
    required: true
  date:
    # 'yyyy-mm-dd'
    type: string
    required: true
  meal-period:
    # 'breakfast' | 'lunch' | 'dinner'
    type: string
    required: true
  party-size:
    type: number
    default: 2
runs:
  using: 'node16'
  main: './index.mjs'
