name: 'Check dland dining availability'
inputs:
  pushover-token:
    type: string
    required: true
  pushover-user:
    type: string
    required: true
  disney-swid:
    type: string
    required: true
runs:
  using: 'node16'
  main: './index.mjs'
