name: Artifacts Demo
on: push
jobs:
  upload-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.txt
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-demo-output
          path: output.txt
